name: movie_watch_list
description: An application for saving videos to watch later.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  retrofit: 4.0.3
  equatable: 2.0.5
  json_annotation: 4.8.0
  dio: 5.4.0
  flutter_bloc: 8.1.2
  get_it: 7.6.0
  cached_network_image: 3.2.3
  flutter_staggered_animations: 1.1.1
  shimmer: 3.0.0
  flutter_svg: 1.1.6
  auto_size_text: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: 6.0.0+3
  build_runner: 2.3.0

flutter:

  uses-material-design: true

  assets:
      - assets/svg/no_connection.svg
      - assets/svg/server_side_error.svg
      - assets/svg/error.svg
      - assets/svg/timeout.svg
      - assets/svg/warning.svg
      - assets/svg/no_image.svg

  fonts:
   - family: Muli
     fonts:
       - asset: assets/font/muli.ttf