name: movie_watch_list
description: An application for saving videos to watch later.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  retrofit: 4.0.3
  equatable: 2.0.5
  dio: 5.4.0
  flutter_bloc: 8.1.2
  get_it: 7.6.7
  cached_network_image: 3.3.1
  flutter_staggered_animations: 1.1.1
  shimmer: 3.0.0
  flutter_svg: 1.1.6
  auto_size_text: 3.0.0
  injectable: 2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.2
  retrofit_generator: 8.0.6
  build_runner: 2.4.8
  injectable_generator: 2.4.1

flutter:

  uses-material-design: true

  assets:
      - assets/svg/no_connection.svg
      - assets/svg/server_side_error.svg
      - assets/svg/error.svg
      - assets/svg/timeout.svg
      - assets/svg/warning.svg
      - assets/svg/no_image.svg

  fonts:
   - family: Muli
     fonts:
       - asset: assets/font/muli.ttf